name: dockerhub

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    # timezone: UTC
    # 避開整點時間，因為有可能會有時間上的延誤
    - cron: '40 16 * * *'

concurrency:
  group: dockerhub-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: liskin/gh-workflow-keepalive@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./build
          push: true
          tags: taichunmin/serveo:latest